"""usbc-dual-rail layout — extends usbc-3v3's known-good 48×30 layout to a
50×30 board, adding a yellow 5 V power-good LED row above the existing
green 3.3 V LED. The right-edge gains a second 2-pin output header for
the raw 5 V rail.

The four marker blocks below are auto-generated by
``circuit_toolkit.builders.extract_layout`` from the .kicad_pcb after each
GUI session. Hand-curated artefacts live outside those blocks:
``ref_text_overrides``, ``pad_zone_full``, ``outline``.
"""

# Hand-curated (extract_layout leaves these alone)
ref_text_overrides = {
    "R2": (9.0, 22.8),
}

pad_zone_full = [
    ("J1", "B7"), ("J1", "A8"),
]

outline = {"shape": "rect", "x": 0.0, "y": 0.0, "w": 50.0, "h": 30.0}


# === auto-generated positions ===
positions = {
    "J1": (5.5, 15, 270),
    "J2": (45, 11, 0),
    "J3": (45, 19, 0),
    "U1": (22, 15, 270),
    "D1": (37, 19, 0),
    "D2": (37, 11, 0),
    "R1": (9, 8.5, 0),
    "R10": (33.5, 11, 0),
    "R2": (9, 21.5, 0),
    "R3": (33.5, 19, 0),
    "C1": (13, 10.5, 0),
    "C2": (30, 10.5, 0),
    "C3": (30, 19.5, 0),
    "H1": (3, 3, 0),
    "H2": (47, 27, 0),
}
# === end positions ===


# === auto-generated tracks ===
tracks = [
    ('GND', 9.545, 19.32, 9.545, 18.25, 0.25, 'F.Cu'),
    ('GND', 9.545, 13.25, 7.5, 13.25, 0.25, 'F.Cu'),
    ('GND', 9.545, 10.68, 9.545, 11.75, 0.25, 'F.Cu'),
    ('GND', 9.545, 14.25, 7.5, 14.25, 0.25, 'F.Cu'),
    ('GND', 8.63, 19.32, 9.545, 19.32, 0.25, 'F.Cu'),
    ('GND', 8.63, 10.68, 9.545, 10.68, 0.25, 'F.Cu'),
    ('GND', 9.545, 16.25, 7.5, 16.25, 0.25, 'F.Cu'),
    ('VBUS', 11.8, 10.5, 11.8, 19.5, 0.5, 'F.Cu'),
    ('VBUS', 11.8, 11.85, 19.7, 11.85, 0.8, 'F.Cu'),
    ('VBUS', 9.545, 17.45, 11.8, 17.45, 0.3, 'F.Cu'),
    ('VBUS', 9.545, 12.55, 11.8, 12.55, 0.3, 'F.Cu'),
    ('CC1', 9.545, 13.75, 10.87, 13.75, 0.3, 'F.Cu'),
    ('CC1', 7, 8.5, 8.49, 8.5, 0.3, 'F.Cu'),
    ('CC1', 7, 13.75, 7, 8.5, 0.3, 'B.Cu'),
    ('CC1', 10.87, 13.75, 7, 13.75, 0.3, 'B.Cu'),
    ('CC2', 10.87, 16.75, 10.87, 16, 0.3, 'F.Cu'),
    ('CC2', 9.545, 16.75, 10.87, 16.75, 0.3, 'F.Cu'),
    ('CC2', 7, 21.5, 8.49, 21.5, 0.3, 'F.Cu'),
    ('CC2', 10.87, 16, 7, 16, 0.3, 'B.Cu'),
    ('CC2', 7, 16, 7, 21.5, 0.3, 'B.Cu'),
]
# === end tracks ===


# === auto-generated vias ===
vias = [
    ('CC1', 10.87, 13.75, 0.4, 0.8),
    ('CC1', 7, 8.5, 0.4, 0.8),
    ('CC2', 7, 21.5, 0.4, 0.8),
    ('CC2', 10.87, 16, 0.4, 0.8),
]
# === end vias ===


# === auto-generated zones ===
zones = [
    {
        "net": 'GND',
        "layer": 'F.Cu',
        "polygon": [(1, 1), (49, 1), (49, 29), (1, 29)],
        "min_thickness": 0.25,
        "pad_connection": 'thermal',
    },
]
# === end zones ===
